"""
VENDORED from jsierrahoopshype/hoopshype-yt-quotes, branch
claude/youtube-quote-extractor-pcYe7, commit 8819e4e, file quote_extractor.py.

Generated by pressers_v2/tools/vendor_ytq.py. Do not edit by hand: every
definition below is copied byte for byte so pressers quotes are extracted,
timestamped and rendered exactly like yt-quotes. The only change is the
speaker rule appended to PROMPT at the end of this file.
"""

import json
import math
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

from google.genai import types

MODEL = "gemini-3.1-flash-lite"


ROOT = Path(__file__).parent


OUTPUT_DIR = ROOT / "output"


PROMPT = """You are watching an NBA YouTube show. Extract the editorially strongest quotes about NBA trades, free agency, player movement, team dynamics, front office, contracts, player legacy, coaching, or playoff issues.

NEWS VALUE: When ranking quotes for inclusion, prefer quotes that contain news (an opinion on a future move, a roster need, a player evaluation that affects trade/free-agency speculation, a specific coaching critique, an admission of regret, a specific prediction) over quotes that are pure analysis or recap. Both are extractable when they're editorially compelling, but news-value quotes are the ones HoopsHype readers seek out — they become trade rumor articles, headlines, social posts. A coach saying "we need another ball-handler" is news. The same coach saying "we played a system that worked" is analysis. Both can be included, but if you're choosing between two quotes of similar quality, take the news one.

Hard rules — these are limits, not targets:

- LENGTH: Capture the speaker's FULL thought, including the setup, the supporting reasoning, and the conclusion — not just the punchline. Err on the side of LONGER quotes. A good quote usually runs 80-200 words: enough to include why the speaker thinks what they think, not just the headline claim. Short 20-40 word quotes should be rare, reserved for genuinely punchy standalone lines. When a speaker builds an argument across several sentences, keep the whole arc together as ONE quote rather than clipping it to the strongest sentence. Hard upper bound: 280 words (longer gets split downstream). The most common length mistake is quoting too little — including the claim but dropping the reasoning that makes it editorially valuable.
- PLAYER NAMES: Use standard NBA reporting spellings for player and team names. Examples: Mikal Bridges (not Michael), Karl-Anthony Towns or KAT (not Cat), Scottie Barnes (not Burns), Jrue Holiday, Donovan Mitchell, Mikael Pereira, Tyrese Maxey, Cade Cunningham, Jalen Brunson, Jaylen Brown, Jayson Tatum. Apply this to all player names across the league.
- ONE TOPIC PER QUOTE (WITHIN): Each individual quote must stay on a single subject — one player, one team, one story, one argument. If a speaker pivots within their answer to a new player or team or argument, that pivot is a new quote with its own rank and timestamp. Do not merge two topics into one quote.
- DO NOT use this rule to cap how many quotes one player appears in. A speaker discussing Anthony Edwards' shot selection in one segment AND Anthony Edwards' need for a ball-handler in a different segment is TWO substantively different quotes (one is player development, one is roster need). Extract both. The rule is about not bundling, not about quota-per-name.
- CONTIGUOUS QUOTES ONLY: Each quote must be a single uninterrupted span of speech from one speaker (or, for dialogue, from two speakers exchanging contiguously). Do NOT join non-adjacent passages. Do NOT skip middle content and rejoin opening and closing fragments. Do NOT condense a long monologue by cutting the middle. If a passage runs past the 280-word cap, return a contiguous excerpt of it (start at point X, end at point Y, both inside the same continuous speech segment) — never fabricate continuity by stitching separated text together. For multi-speaker quotes (text_blocks), each speaker's contribution within their block must also be contiguous — do not stitch a speaker's earlier and later statements into one block. Example —
  BAD (stitches non-adjacent passages from the same long monologue): "I think the Knicks have a real shot this year because Brunson is just on another level... and that's why I'd take them over the Cavs in a seven-game series."
  (Between those two sentences the speaker actually talked for 3 minutes about Mikal Bridges, Karl-Anthony Towns, and the coaching staff — none of which appears in the quote above.)
  GOOD (one contiguous span): "I think the Knicks have a real shot this year because Brunson is just on another level. Look at what he did in Game 5 — 41 points, the closing stretch, the way he got to the rim. That's the kind of run no one was projecting from him this season."
- MONOLOGUES: When a speaker delivers a long multi-subject monologue, split it by SUBJECT (one quote per player/team/story per the ONE TOPIC rule), but within each subject keep the speaker's full treatment of that subject — the setup, reasoning, and conclusion — as one substantial quote. Do not reduce a rich two-minute take on a single subject down to one sentence. Each subject-scoped quote should be as long as the speaker's actual continuous argument on that subject, up to the 280-word cap.

How many quotes to return — TARGET DENSITY, not a ceiling. THE MOST COMMON FAILURE MODE IS UNDER-EXTRACTION: missing strong quotes by being too selective. Lean toward inclusion whenever content is editorially worthwhile.

For genuinely substantive content, aim for roughly one quote per 3-4 minutes of substantive discussion:

- Under 30 min: 5-10 quotes is normal for an editorial segment; punchy shows with rapid-fire takes can yield 10+. Returning 1-2 from a 20-minute editorial segment is almost certainly under-extraction.
- 30 to 60 min: a typical NBA podcast in this range should yield 10-20 quotes. A 45-minute interview with a returning All-Star producing only 3-4 quotes is severe under-extraction — you skipped real material.
- 60+ min (this video may be sent to you in 60-minute chunks): apply the SAME per-chunk density. Each 60-minute chunk of rich content should yield 10-20 quotes. A 90-minute video processed as 2 chunks produces roughly 20-30 quotes total.

Hard cap: 20 quotes per request (or per chunk for chunked videos). Empty array is acceptable ONLY for thin / non-editorial content (pure sponsor reads, recap-only highlights, intros). For substantive editorial content, single-digit quote counts on a 30+ minute video are almost always wrong.

The "no padding" rule stays — do NOT extract weak filler to hit a target. But the bar to clear is "is this editorially compelling?" not "is this quote among the top 5 in the video?". When in doubt about a substantive take, INCLUDE IT.

Editorial rules:

- Identify the speaker by name when shown on screen, named in chyrons, named in the video title, or clearly addressed by another speaker. Otherwise return an empty string "" for the speaker. Never invent or guess a speaker name. Never use descriptors like "man with beard" or "guy in red hoodie" — that is not a speaker identification. Never use the literal value "Unknown" or "Unknown speaker" — leave the field empty.
- MULTI-SPEAKER QUOTES: Use the "text_blocks" field WHENEVER two or more identified speakers each contribute more than about 5 words to the same subject within the same minute of audio. This threshold is low on purpose — short back-and-forth exchanges should render as dialogue, not as a single squished block. Both speakers count as long as their contributions are substantive (an attributed setup question by a host like "What did you think of that play?" followed by a substantive answer DOES qualify). Record each contribution as a paragraph in chronological order; the top-level "speaker" field is the speaker with the longest contribution; the "speakers" array lists all contributing speakers in order; "quote" is left empty. If the speakers shift to a different player/team/story, split into separate quotes per the ONE TOPIC PER QUOTE rule — do not bundle multiple subjects under one multi-speaker quote. Example of a short exchange that MUST use text_blocks:
  Speaker A: "Did you see that no-call on Brunson at the end?"
  Speaker B: "Tony Brothers blew it. That's a foul every day of the week. They make the free throw, game over."
  -> render as two text_blocks, not a single combined quote.
- Provide a start timestamp in MM:SS or H:MM:SS format pointing at the moment the quote begins.
- For each quote, write a "summary_phrase": a 5-12 word headline that describes the SUBSTANCE of what the speaker is saying, in concrete terms. Examples:
    - "why Embiid can't have a 'legacy game' in round 1"
    - "Max Strus's defensive transformation in Cleveland"
    - "DeAndre Ayton on his last straw in Portland"
  Do NOT use generic category labels like "player legacy", "team dynamics", "trades", "coaching", "playoffs". The summary_phrase must name a specific player, team, story, or argument — not a category.
- For each quote, list every player, coach, or front-office name mentioned IN THE QUOTE TEXT in the "names_mentioned" array. Use the exact substring spelling that appears in your cleaned quote text. Do not include team names, hosts who don't appear in the quote body, or the speaker's own name unless they refer to themselves in third person inside the quote.
- For each quote, write an "excerpt" field: a verbatim string of UP TO 18 WORDS pulled directly from the quote body. Pick the punchiest / most quotable single line — the standalone sentence that would work as a pull-quote in a headline. The excerpt MUST appear word-for-word in the quote text (or, for multi-speaker quotes, in any one speaker's text_blocks contribution — pick the most quotable line, not necessarily the longest speaker's). Do not paraphrase, condense, or add punctuation that isn't there. If no obvious 18-word pull-quote exists (single-sentence quotes, all rambling, etc.), leave excerpt as an empty string "".
- FILLER CLEANUP: Strip conversational noise so the quote reads like lightly edited print. Remove "uh", "um", "er", "ah" and variants. Remove "you know" when used as filler (keep it when it's a real question or phrase). Remove "like" when used as filler or hedging (keep it as a real verb or comparison). Remove "I mean" when used to restart a thought. Remove "kind of" and "sort of" when used as filler. Collapse repeated words from false starts ("the the", "we we"). Resolve mid-sentence trailing-off restarts to the speaker's completed thought (e.g. "if he goes home, he's not -- he can be the guy" -> "if he goes home, he can be the guy"). Preserve the speaker's voice and emphasis. Do not paraphrase or change meaning. Example —
  Before: "If he leaves LA, uh, Cleveland. I think it's full circle, going home again, um, joining a team that, as we saw, uh, last night, um, once again, you know, obviously Donovan Mitchell going off..."
  After: "If he leaves LA, Cleveland. I think it's full circle, going home again, joining a team that, as we saw last night, once again, obviously Donovan Mitchell going off..."
- Preserve the speaker's meaning. Do not exaggerate their tone. Do not fabricate.
- Skip play-by-play recap, sponsor reads, intros, outros, generic opinions, and recycled talking points unless phrased forcefully.
- LANGUAGE: If the video's primary spoken language is NOT English, translate everything in your JSON output to English: the cleaned quote text, the summary_phrase, the excerpt, every text_blocks "text" field, and the speaker / speakers names (transliterate to standard English-language reporting spellings). The whole output must read as if the video were originally in English. ALSO populate, for each quote where translation occurred, a "verbatim_original_language" field containing the cleaned quote body in the ORIGINAL language exactly as spoken (with the same filler-cleanup applied as the English version). For English-source videos, omit "verbatim_original_language" or leave it as an empty string. The "quote", "text_blocks.text", "summary_phrase", and "excerpt" fields ALWAYS contain English regardless of source language.
- HALLUCINATION GUARD: Begin your JSON with a "video_title" field that ECHOES BACK EXACTLY the YouTube title supplied above (the line starting with "YouTube title:"). Preserve case, punctuation, and emoji. This is a sanity check — if the content of your analysis doesn't match the title we provided, the response will be rejected and the video will be retried.

Return ONLY valid JSON, no surrounding text or markdown fences:

{
  "video_title": "exact echo of the YouTube title supplied above",
  "speakers_seen": ["names you saw or heard, in order of appearance"],
  "quotes": [
    {
      "rank": 1,
      "speaker": "string (empty if not confidently identifiable; longest contributor for multi-speaker quotes)",
      "speakers": ["only populate for multi-speaker quotes; omit or leave empty otherwise"],
      "timestamp": "MM:SS",
      "summary_phrase": "5-12 word specific headline naming a player, team, or story",
      "names_mentioned": ["LeBron James", "Mikal Bridges"],
      "excerpt": "up to 18 words pulled verbatim from the quote body; empty string if no clean pull-quote",
      "quote": "cleaned quote text in ENGLISH (leave empty when using text_blocks)",
      "verbatim_original_language": "cleaned quote text in the SOURCE language; omit or empty for English-source videos",
      "text_blocks": [
        {"speaker": "X", "text": "X's contribution in ENGLISH"},
        {"speaker": "Y", "text": "Y's contribution in ENGLISH"}
      ]
    }
  ]
}"""


SPLIT_PROMPT = """You are editing a single quote from an NBA YouTube show that is too long or covers too many topics. Split it into 1 to 4 standalone sub-quotes.

Hard rules:

- Each sub-quote should match the natural shape of its content. A single punchy line is fine; so is a 200-word argument. Don't force any target length. Hard upper bound: 280 words per sub-quote (anything longer will be split again).
- PLAYER NAMES: Use standard NBA reporting spellings for player and team names. Examples: Mikal Bridges (not Michael), Karl-Anthony Towns or KAT (not Cat), Scottie Barnes (not Burns), Jrue Holiday, Donovan Mitchell, Mikael Pereira, Tyrese Maxey, Cade Cunningham, Jalen Brunson, Jaylen Brown, Jayson Tatum. Apply this to all player names across the league.
- Each sub-quote covers a single subject — one player, one team, one story, one argument.
- CONTIGUOUS ONLY: Each sub-quote must be a single uninterrupted span of speech from the original. Do not stitch the opening and closing sentences of the original together while skipping middle content. If the substantive content for a subject is itself non-contiguous in the original, pick the strongest single contiguous span and drop the rest rather than fabricating continuity.
- Use the SAME timestamp as the original quote for every sub-quote. Use the SAME speaker (or speakers) unless the original was multi-speaker and a particular sub-quote only includes one of them.
- For each sub-quote, write a "summary_phrase": a 5-12 word headline naming the specific player, team, story, or argument. Do not use generic category labels.
- For each sub-quote, list every player, coach, or front-office name mentioned in the sub-quote text in "names_mentioned", using the exact substring spelling from your cleaned text.
- For each sub-quote, write an "excerpt" of up to 18 words pulled verbatim from the sub-quote body (or, for multi-speaker sub-quotes, from any speaker's contribution). Pick the punchiest standalone line. Empty string when no clean pull-quote exists.
- If a sub-quote is multi-speaker dialogue on the same subject, populate "text_blocks" with one entry per speaker contribution (in order) and leave "quote" empty. The "speaker" field becomes the longest contributor in that sub-quote; populate "speakers" with the list. Single-speaker sub-quotes use "quote" only.
- If the speaker is not confidently identifiable, leave "speaker" empty (do not write "Unknown").
- Clean only obvious filler ("um", "uh", "you know", false starts) and punctuation. Preserve the speaker's meaning. Do not exaggerate. Do not fabricate.
- Drop weak segments rather than padding. Returning fewer sub-quotes is better than returning weak ones.

Return ONLY valid JSON, no surrounding text or markdown fences. The output is a JSON ARRAY at the top level (not an object):

[
  {
    "speaker": "string",
    "speakers": ["only for multi-speaker sub-quotes"],
    "timestamp": "MM:SS",
    "summary_phrase": "5-12 word specific headline",
    "names_mentioned": ["LeBron James"],
    "excerpt": "up to 18 words pulled verbatim; empty string if no clean pull-quote",
    "quote": "cleaned quote text (empty if using text_blocks)",
    "text_blocks": [
      {"speaker": "X", "text": "X's contribution"},
      {"speaker": "Y", "text": "Y's contribution"}
    ]
  }
]"""


MAX_QUOTES_AFTER_SPLIT = 30


# Quotes over this length get split into sub-quotes. Raised from 220 to 280
# to preserve longer editorial arguments — 150-200 word quotes are normal
# for podcasts where a host builds a multi-sentence case, and forcing them
# through the splitter was breaking up coherent thoughts.
MAX_QUOTE_WORDS_BEFORE_SPLIT = 280


# Footer link appended to every published digest.md. Uses HTML so it opens
# in a new tab in both GitHub blob and GitHub Pages renderers, matching the
# style of the Source and timestamp links inside per-video markdown.
DIGEST_CLOSING_LINE = (
    '<a href="https://www.youtube.com/feed/subscriptions" target="_blank" '
    'rel="noopener">CHECK OTHER YOUTUBE PODCASTS HERE</a>'
)


SPLIT_WORKERS = 4   # concurrent splitter calls within a single video


# Long-video chunking: when a video exceeds CHUNK_DURATION_SECS we run Gemini
# once per 60-min chunk (passing start_offset / end_offset through Part's
# video_metadata) and merge the quote lists. Videos longer than
# CHUNK_DURATION_SECS * MAX_CHUNKS get the existing too-long treatment.
CHUNK_DURATION_SECS = 60 * 60         # 60 min per chunk


MAX_CHUNKS = 4                        # cap chunking at 4h total video length


# Substrings (uppercased) in an exception's str() that count as transient
# network/server errors and should be retried with the standard backoff.
_TRANSIENT_MESSAGE_PATTERNS = (
    "UNAVAILABLE",
    "RESOURCE_EXHAUSTED",
    "INTERNAL",
    "SERVER DISCONNECTED",
    "CONNECTION RESET",
    "CONNECTION ABORTED",
    "READ TIMED OUT",
    "REMOTE END CLOSED CONNECTION",
    "READERROR",
    "REMOTEPROTOCOLERROR",
    "CONNECTERROR",
    "READTIMEOUT",
    "CONNECTTIMEOUT",
)


def log(msg: str) -> None:
    print(f"[{datetime.now().strftime('%H:%M:%S')}] {msg}", flush=True)


def timestamp_to_seconds(ts: str) -> int:
    parts = (ts or "").strip().split(":")
    try:
        nums = [int(p) for p in parts]
    except ValueError:
        return 0
    if len(nums) == 3:
        return nums[0] * 3600 + nums[1] * 60 + nums[2]
    if len(nums) == 2:
        return nums[0] * 60 + nums[1]
    return nums[0] if nums else 0


def _seconds_to_timestamp(secs: int) -> str:
    """Inverse of timestamp_to_seconds. Returns MM:SS for <1h, H:MM:SS for >=1h.
    Used by the chunked-video path to translate chunk-relative timestamps that
    Gemini returns into absolute timestamps for the whole video.
    """
    if secs is None or secs < 0:
        secs = 0
    hours = secs // 3600
    mins = (secs % 3600) // 60
    s = secs % 60
    if hours > 0:
        return f"{hours}:{mins:02d}:{s:02d}"
    return f"{mins:02d}:{s:02d}"


def _compute_chunks(duration_secs: int) -> list | None:
    """Return a list of (start_offset_secs, end_offset_secs) tuples covering
    the video's duration in CHUNK_DURATION_SECS-long slices. Returns None
    when the video exceeds MAX_CHUNKS * CHUNK_DURATION_SECS (the caller
    should mark it too-long).

    Short videos (<= CHUNK_DURATION_SECS) get [(None, None)] — a single
    pass with no video_metadata, identical to the existing whole-video
    behaviour. Videos with unknown duration (<= 0) also get [(None, None)]
    since chunking would be guesswork.
    """
    if duration_secs is None or duration_secs <= 0:
        return [(None, None)]
    if duration_secs <= CHUNK_DURATION_SECS:
        return [(None, None)]
    if duration_secs > CHUNK_DURATION_SECS * MAX_CHUNKS:
        return None
    n_chunks = math.ceil(duration_secs / CHUNK_DURATION_SECS)
    return [
        (i * CHUNK_DURATION_SECS,
         min((i + 1) * CHUNK_DURATION_SECS, duration_secs))
        for i in range(n_chunks)
    ]


def video_id_from_url(url: str) -> str:
    m = re.search(r"(?:v=|youtu\.be/|/shorts/|/embed/)([A-Za-z0-9_-]{11})", url or "")
    return m.group(1) if m else ""


def _normalize_title(title: str) -> str:
    """Lowercase, strip punctuation/emoji/everything non-alphanumeric, collapse
    whitespace. Used for the hallucination guard's word-overlap comparison."""
    if not title:
        return ""
    lower = title.lower()
    stripped = re.sub(r"[^a-z0-9\s]+", " ", lower)
    return re.sub(r"\s+", " ", stripped).strip()


def _title_word_overlap(expected: str, got: str) -> float:
    """Fraction of expected's distinct words that also appear in got's words.
    Returns 1.0 when expected has no analyzable words (pure-emoji titles
    etc.), so the check doesn't false-positive on uncheckable inputs.
    """
    exp_words = set(_normalize_title(expected).split())
    if not exp_words:
        return 1.0
    got_words = set(_normalize_title(got).split())
    return len(exp_words & got_words) / len(exp_words)


HALLUCINATION_OVERLAP_THRESHOLD = 0.70  # strictly greater; 0.70 itself is rejected


def _publish_date(video: dict) -> str:
    """Return the video's YYYY-MM-DD UTC publish date for routing output to
    output/<date>/. Falls back to today's UTC date if publishedAt is missing
    or unparseable so we never crash here.
    """
    iso = (video.get("published") or "").strip()
    if iso:
        try:
            dt = datetime.fromisoformat(iso.replace("Z", "+00:00"))
            return dt.astimezone(timezone.utc).strftime("%Y-%m-%d")
        except (ValueError, TypeError):
            pass
    return datetime.now(timezone.utc).strftime("%Y-%m-%d")


def _video_day_dir(video: dict) -> Path:
    """Where this video's outputs (md, json, markers, ATTEMPTS) land on disk.

    One-off videos (video["is_one_off"] = True) route to
    output/oneoffs/<pub_date>/ so editorial rotation digests stay clean.
    Rotation videos use output/<pub_date>/ as before.
    """
    pub_date = _publish_date(video)
    if video.get("is_one_off"):
        return OUTPUT_DIR / "oneoffs" / pub_date
    return OUTPUT_DIR / pub_date


def call_gemini(
    client,
    url: str,
    video_title: str = "",
    known_speakers: list | None = None,
    start_offset_secs: int | None = None,
    end_offset_secs: int | None = None,
) -> tuple[str, object]:
    """Send the video to Gemini and return (raw_text, usage_metadata).

    The actual YouTube title is prepended to the prompt so Gemini can echo
    it back in its JSON. The caller compares the echo against the expected
    title to catch hallucinated full-output responses.

    When the channel has a configured known_speakers list, a hint line is
    prepended to anchor recurring-host name spellings so Gemini doesn't
    substitute similar-sounding names (e.g. Allie Clifton -> Allie LaForce).

    When start_offset_secs / end_offset_secs are provided, a VideoMetadata
    object is attached to the video Part so Gemini only analyzes that slice
    of the video (used by the long-video chunking path). Timestamps Gemini
    returns are relative to start_offset_secs; the caller adds the offset
    back to get absolute timestamps.
    """
    parts = [f"YouTube title: {video_title}"]
    if known_speakers:
        joined = ", ".join(known_speakers)
        parts.append(
            f"KNOWN HOSTS for this channel: {joined}. Other speakers may appear "
            "as guests, but when identifying the regular hosts, use these exact "
            "spellings. Do NOT substitute similar-sounding names (e.g., "
            "Allie LaForce, Allison Williams)."
        )
    if start_offset_secs is not None and end_offset_secs is not None:
        parts.append(
            f"CHUNK CONTEXT: this is one slice of a longer video, covering seconds "
            f"{start_offset_secs} through {end_offset_secs} (relative to the original). "
            f"Return timestamps relative to the slice (start at 0:00 = the slice's "
            f"first second). The pipeline will translate them to absolute timestamps."
        )
    prefixed_prompt = "\n\n".join(parts) + "\n\n" + PROMPT
    video_part = types.Part.from_uri(file_uri=url, mime_type="video/mp4")
    if start_offset_secs is not None or end_offset_secs is not None:
        start_str = f"{start_offset_secs or 0}s"
        end_str = f"{end_offset_secs}s" if end_offset_secs is not None else None
        try:
            video_part.video_metadata = types.VideoMetadata(
                start_offset=start_str,
                end_offset=end_str,
            )
        except (AttributeError, TypeError):
            # If the SDK version doesn't expose VideoMetadata yet, fall back
            # to whole-video analysis. The post-merge timestamp adjustment
            # would then be wrong, but at least we don't crash. Log loudly
            # so this surfaces in the run output.
            log(f"  [chunk] WARN: types.VideoMetadata unavailable in this SDK; "
                f"falling back to whole-video for offsets ({start_str}, {end_str})")
    response = client.models.generate_content(
        model=MODEL,
        contents=[video_part, prefixed_prompt],
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            temperature=0.3,
            media_resolution=types.MediaResolution.MEDIA_RESOLUTION_LOW,
        ),
    )
    return (response.text or ""), response.usage_metadata


def gemini_error_status(exc: Exception) -> int | None:
    code = getattr(exc, "code", None) or getattr(exc, "status_code", None)
    if isinstance(code, int):
        return code
    msg = str(exc)
    m = re.search(r"\b(4\d\d|5\d\d)\b", msg)
    return int(m.group(1)) if m else None


def is_token_limit_error(exc: Exception) -> bool:
    msg = str(exc).lower()
    return "token" in msg and ("limit" in msg or "exceed" in msg or "too" in msg)


class SpendingCapExhausted(Exception):
    """Raised when a 429 indicates a project spending cap / daily quota is
    exhausted and won't recover within this run. Distinguished from regular
    transient 429s (per-minute rate limits) by the error message: spending
    caps surface phrases like "spending cap", "quota exceeded", or
    "exceeded your current quota" that the underlying httpx exception
    carries through. The script bails out of the queue on first occurrence
    instead of burning the rest of the rotation hammering a dead bucket.
    """


# Substrings (uppercased) in an exception's str() that indicate a NON-RECOVERABLE
# quota / spending-cap exhaustion. These trump _TRANSIENT_MESSAGE_PATTERNS so a
# 429 with one of these strings raises SpendingCapExhausted immediately rather
# than burning retries.
_SPENDING_CAP_PATTERNS = (
    "SPENDING CAP",
    "EXCEEDED YOUR CURRENT QUOTA",
    "QUOTA EXCEEDED",
)


def _is_spending_cap_error(exc: Exception) -> bool:
    msg = str(exc).upper()
    return any(p in msg for p in _SPENDING_CAP_PATTERNS)


class TransientServerOverload(Exception):
    """Raised when a Gemini 503 UNAVAILABLE / 500 INTERNAL survives the full
    5-attempt in-call retry budget. The video itself is fine — Gemini's
    servers were just temporarily overloaded — so the caller should treat
    it as "deferred to next run" rather than marking it failed and
    eventually writing FAILED.txt. Distinct from regular failed-other so
    these don't count against the per-video retry cap.
    """


def _is_deferred_transient_error(exc: Exception) -> bool:
    """True for terminal 503 UNAVAILABLE / 500 INTERNAL errors that survived
    all retries. Other transient classes (httpx ReadError, ConnectionReset,
    READ TIMED OUT, etc.) still get the existing failed-other treatment —
    only Gemini server-overload signals get the deferred treatment per
    Jorge's spec.
    """
    status = gemini_error_status(exc)
    if status in (500, 503):
        return True
    msg = str(exc).upper()
    return "UNAVAILABLE" in msg or "500 INTERNAL" in msg


def _is_transient_gemini_error(exc: Exception) -> bool:
    """True for retryable errors: HTTP 429/500/503, httpx network errors,
    and any message containing one of _TRANSIENT_MESSAGE_PATTERNS.

    Note: callers should check _is_spending_cap_error FIRST, since a 429
    with a quota-exhaustion message is non-recoverable in this run even
    though it looks transient by status code alone.
    """
    status = gemini_error_status(exc)
    if status in (429, 500, 503):
        return True
    try:
        import httpx
        if isinstance(exc, (
            httpx.ReadError,
            httpx.RemoteProtocolError,
            httpx.ConnectError,
            httpx.ReadTimeout,
            httpx.ConnectTimeout,
        )):
            return True
    except ImportError:
        pass
    msg = str(exc).upper()
    for pattern in _TRANSIENT_MESSAGE_PATTERNS:
        if pattern in msg:
            return True
    return False


def call_gemini_with_retry(
    client,
    url: str,
    video_title: str = "",
    known_speakers: list | None = None,
    start_offset_secs: int | None = None,
    end_offset_secs: int | None = None,
) -> tuple[str, object]:
    """Wrap call_gemini with the same 5s/15s/45s/120s/300s retry policy as the splitter.

    Retries on 429, 500, 503, or messages containing UNAVAILABLE /
    RESOURCE_EXHAUSTED / INTERNAL. Non-retryable errors (400/token-limit,
    other 4xx) propagate immediately so the caller can map them to
    too-long or failed-other.
    """
    backoffs = [5, 15, 45, 120, 300]
    for attempt, sleep_s in enumerate(backoffs, start=1):
        try:
            return call_gemini(client, url, video_title, known_speakers,
                               start_offset_secs=start_offset_secs,
                               end_offset_secs=end_offset_secs)
        except Exception as e:
            if _is_spending_cap_error(e):
                log(f"  [main] [SPENDING CAP] {e}")
                raise SpendingCapExhausted(str(e)) from e
            if not _is_transient_gemini_error(e):
                raise
            if attempt < len(backoffs):
                log(f"  [main] transient error on attempt {attempt}/5, sleeping {sleep_s}s: {e}")
                time.sleep(sleep_s)
            else:
                log(f"  [main] giving up after 5 attempts: {e}")
                # Terminal 503/500 -> defer the video (no marker written;
                # retried fresh next run). Other terminal transients
                # (httpx ReadError, etc.) keep the existing failed-other
                # path so genuine flakiness still counts toward the cap.
                if _is_deferred_transient_error(e):
                    log(f"  [DEFERRED] Gemini server overload after retries; will retry next run")
                    raise TransientServerOverload(str(e)) from e
                raise


def _word_count(text: str) -> int:
    return len((text or "").split())


def _canonical_quote_text(quote: dict) -> str:
    """Return the full body of a quote regardless of single-speaker ("quote")
    or multi-speaker ("text_blocks") shape. Used for length, dedupe, and
    Slack top-quote extraction.
    """
    blocks = quote.get("text_blocks") or []
    if blocks:
        return " ".join(
            (b.get("text") or "").strip() for b in blocks if isinstance(b, dict)
        ).strip()
    return (quote.get("quote") or "").strip()


def _needs_split(quote: dict) -> bool:
    return _word_count(_canonical_quote_text(quote)) > MAX_QUOTE_WORDS_BEFORE_SPLIT


def split_quote(client, quote: dict) -> tuple[list, str]:
    """Run a text-only Gemini call to split one oversized quote.

    Returns (sub_quotes, status) where status is:
      "split"     — splitter produced multiple sub-quotes
      "unchanged" — splitter ran but returned 0/1 usable sub-quotes,
                    or its response was unparseable
      "failed"    — API error: either a non-retryable 4xx, or transient
                    503/429 that didn't recover within 5 attempts

    On any non-"split" outcome, sub_quotes is [quote] so the caller can
    extend its list verbatim and the original quote survives.
    """
    speaker = quote.get("speaker") or ""
    timestamp = quote.get("timestamp") or "0:00"
    canonical = _canonical_quote_text(quote)
    blocks = quote.get("text_blocks") or []
    speakers_list = quote.get("speakers") or []
    if blocks:
        formatted_blocks = []
        for b in blocks:
            sp = (b.get("speaker") or "").strip()
            tx = (b.get("text") or "").strip()
            if sp:
                formatted_blocks.append(f"**{sp}:** \"{tx}\"")
            else:
                formatted_blocks.append(f'"{tx}"')
        body = "\n\n".join(formatted_blocks)
        speakers_line = f"Speakers: {', '.join(speakers_list or [b.get('speaker','') for b in blocks])}\n"
    else:
        body = canonical
        speakers_line = f"Speaker: {speaker}\n" if speaker else ""
    user_text = (
        f"{speakers_line}"
        f"Timestamp: {timestamp}\n"
        f"Original quote ({_word_count(canonical)} words):\n\n{body}"
    )

    backoffs = [5, 15, 45, 120, 300]
    response = None
    for attempt, sleep_s in enumerate(backoffs, start=1):
        try:
            response = client.models.generate_content(
                model=MODEL,
                contents=[SPLIT_PROMPT, user_text],
                config=types.GenerateContentConfig(
                    response_mime_type="application/json",
                    temperature=0.3,
                ),
            )
            break
        except Exception as e:
            if _is_spending_cap_error(e):
                log(f"  [split] [SPENDING CAP] {e}")
                raise SpendingCapExhausted(str(e)) from e
            if not _is_transient_gemini_error(e):
                log(f"  [split] non-retryable error, keeping original: {e}")
                return [quote], "failed"
            if attempt < len(backoffs):
                log(f"  [split] transient error on attempt {attempt}/5, sleeping {sleep_s}s: {e}")
                time.sleep(sleep_s)
            else:
                log(f"  [split] giving up after 5 attempts: {e}")
                return [quote], "failed"

    try:
        parsed = json.loads(response.text or "")
    except Exception as e:
        log(f"  [split] malformed JSON, keeping original: {e}")
        return [quote], "unchanged"

    if isinstance(parsed, dict):
        for key in ("quotes", "sub_quotes", "results"):
            if isinstance(parsed.get(key), list):
                parsed = parsed[key]
                break
    if not isinstance(parsed, list) or not parsed:
        log("  [split] returned no usable sub-quotes; keeping original")
        return [quote], "unchanged"

    out = []
    for sub in parsed:
        if not isinstance(sub, dict):
            continue
        sub_blocks = sub.get("text_blocks") or []
        sub_quote = sub.get("quote") or ""
        if not sub_blocks and not sub_quote.strip():
            continue
        sub_dict = {
            "speaker": sub.get("speaker") or speaker,
            "timestamp": sub.get("timestamp") or timestamp,
            "summary_phrase": sub.get("summary_phrase") or quote.get("summary_phrase", ""),
            "names_mentioned": sub.get("names_mentioned") or quote.get("names_mentioned", []),
            "excerpt": sub.get("excerpt") or "",
            "quote": sub_quote,
        }
        if sub_blocks:
            # Keep only well-formed blocks
            clean_blocks = [
                {"speaker": (b.get("speaker") or "").strip(), "text": (b.get("text") or "").strip()}
                for b in sub_blocks if isinstance(b, dict) and (b.get("text") or "").strip()
            ]
            if clean_blocks:
                sub_dict["text_blocks"] = clean_blocks
                sub_speakers = sub.get("speakers") or [b["speaker"] for b in clean_blocks if b["speaker"]]
                if sub_speakers:
                    sub_dict["speakers"] = sub_speakers
        out.append(sub_dict)
    if len(out) > 1:
        return out, "split"
    if len(out) == 1:
        return out, "unchanged"
    return [quote], "unchanged"


def post_process_quotes(client, quotes: list) -> list:
    """Split oversized quotes (in parallel), then re-rank and cap.

    Splitter calls fan out across SPLIT_WORKERS threads. The final list is
    assembled in the original input order so ranks remain stable, then
    re-numbered 1..N and capped at MAX_QUOTES_AFTER_SPLIT.
    """
    quotes = quotes or []
    counts = {"split": 0, "unchanged": 0, "failed": 0}
    results: list = [None] * len(quotes)

    split_jobs = []
    for i, q in enumerate(quotes):
        if _needs_split(q):
            split_jobs.append((i, q))
        else:
            results[i] = [q]

    if split_jobs:
        with ThreadPoolExecutor(max_workers=SPLIT_WORKERS) as ex:
            future_to_job = {
                ex.submit(split_quote, client, q): (i, q) for i, q in split_jobs
            }
            for fut in as_completed(future_to_job):
                i, q = future_to_job[fut]
                try:
                    subs, status = fut.result()
                except SpendingCapExhausted:
                    # Don't bury the cap signal as a generic split failure;
                    # let it propagate so process_video and _process_one_video
                    # can set the global abort flag.
                    raise
                except Exception as e:
                    log(f"  [split] worker raised {e!r}; keeping original")
                    subs, status = [q], "failed"
                counts[status] += 1
                if status == "split":
                    wc = _word_count(_canonical_quote_text(q))
                    log(f"  [split] quote {i + 1} ({wc} words) -> {len(subs)} sub-quotes")
                results[i] = subs

    out = []
    for r in results:
        out.extend(r if r is not None else [])

    if sum(counts.values()):
        log(
            f"  [split] summary: {counts['split']} split, "
            f"{counts['unchanged']} unchanged, "
            f"{counts['failed']} failed after retries"
        )

    # Dedupe on the cleaned quote body only. Keep first occurrence. The
    # canonical text helper handles both single-speaker "quote" and
    # multi-speaker "text_blocks" shapes.
    seen_bodies = set()
    deduped = []
    for q in out:
        key = _canonical_quote_text(q)
        if key and key in seen_bodies:
            continue
        if key:
            seen_bodies.add(key)
        deduped.append(q)
    if len(deduped) != len(out):
        log(f"  [dedupe] removed {len(out) - len(deduped)} identical quote(s)")
    out = deduped

    if len(out) > MAX_QUOTES_AFTER_SPLIT:
        log(f"  [split] capping {len(out)} quotes at {MAX_QUOTES_AFTER_SPLIT}")
        out = out[:MAX_QUOTES_AFTER_SPLIT]

    for i, q in enumerate(out):
        q["rank"] = i + 1
    return out


def to_markdown(url: str, channel_name: str, data: dict) -> str:
    vid = video_id_from_url(url)
    title = data.get("video_title") or "NBA quotes"
    lines = [
        f"# {title} — *{channel_name}*",
        "",
        f"Source: {url}",
        "",
    ]
    if data.get("speakers_seen"):
        lines.append(f"_Speakers identified: {', '.join(data['speakers_seen'])}_")
        lines.append("")
    for q in data.get("quotes", []):
        secs = timestamp_to_seconds(q.get("timestamp", "0:00"))
        ts_link = f"https://www.youtube.com/watch?v={vid}&t={secs}s" if vid else url
        ts_label = q.get('timestamp', '?')
        rank = q.get('rank', '?')
        speaker = (q.get("speaker") or "").strip()
        summary = (q.get("summary_phrase") or "").strip()
        excerpt = (q.get("excerpt") or "").strip()
        if _is_unknown_speaker(speaker):
            speaker = ""
        # Header format: **N. Speaker — summary — "excerpt"** [timestamp](url)
        # Any of speaker/summary/excerpt may be empty; em-dashes join only
        # present pieces. Plain markdown link for the timestamp so GitHub's
        # renderer applies its own target=_blank rather than us emitting
        # HTML that the sanitizer strips.
        fragments = []
        if speaker:
            fragments.append(speaker)
        if excerpt:
            fragments.append(f'"{excerpt}"')
        if summary:
            fragments.append(summary)
        if fragments:
            inner = " — ".join(fragments)
            header = f"**{rank}. {inner}** [{ts_label}]({ts_link})"
        else:
            header = f"**{rank}.** [{ts_label}]({ts_link})"
        lines.append(header)
        lines.append("")
        names = q.get("names_mentioned") or []
        blocks = q.get("text_blocks") or []
        if blocks:
            for j, block in enumerate(blocks):
                block_speaker = (block.get("speaker") or "").strip()
                block_text = block.get("text") or ""
                bolded = _bold_names(block_text, names)
                if _is_unknown_speaker(block_speaker):
                    lines.append(f"\"{bolded}\"")
                else:
                    lines.append(f"**{block_speaker}:** \"{bolded}\"")
                if j < len(blocks) - 1:
                    lines.append("")  # blank line -> markdown paragraph break
        else:
            body = q.get("quote", "")
            bolded = _bold_names(body, names)
            # Prefix the single-speaker body with the speaker name (when
            # we have one) — Speaker: "text". Mirrors the multi-speaker
            # **Speaker:** "..." convention. Speaker is the same value
            # already shown in the bolded header; intentional repeat.
            if speaker:
                lines.append(f"{speaker}: \"{bolded}\"")
            else:
                lines.append(f"\"{bolded}\"")
        # Plain-text URL as the LAST line of the quote block (after the
        # body, separated by a blank line). Same VIDEO_ID + timestamp the
        # header's markdown link uses — visible and copy-pasteable.
        # Applies uniformly to single- and multi-speaker render paths.
        lines.append("")
        lines.append(ts_link)
        lines.append("")
    return "\n".join(lines)


def _is_unknown_speaker(speaker: str) -> bool:
    """True when the speaker field should be treated as no-attribution.

    Covers empty strings, the literal 'Unknown' / 'Unknown speaker', and
    variants Gemini sometimes returns even though the prompt forbids them
    ('Unknown speaker (man with beard)', 'Unknown host', etc.). The defensive
    check stays in place even after the prompt was updated to require an
    empty string for unidentified speakers.
    """
    if not speaker:
        return True
    lower = speaker.strip().lower()
    if lower.startswith("unknown"):
        return True
    return lower in ("speaker",)


def _bold_names(text: str, names: list) -> str:
    """Wrap every occurrence of each name in **bold** markers.

    Longest names first via a single regex pass so "LeBron James" is bolded
    as one unit instead of "**LeBron** James". Exact substring match,
    case-sensitive, matching the spec.
    """
    valid = [n for n in (names or []) if isinstance(n, str) and n.strip()]
    if not valid or not text:
        return text or ""
    sorted_names = sorted(set(valid), key=len, reverse=True)
    pattern = "|".join(re.escape(n) for n in sorted_names)
    return re.sub(pattern, lambda m: f"**{m.group(0)}**", text)


def write_outputs(video: dict, channel_name: str, data: dict, raw_text: str) -> Path:
    """Write <video_id>.md and <video_id>.json atomically.

    Both files are written first to a sibling .tmp path and then renamed onto
    the canonical name, so a crash mid-write can never leave an empty .md
    visible at the published path. An empty rendered markdown is treated as a
    bug and raises before any file is opened.
    """
    day_dir = _video_day_dir(video)
    day_dir.mkdir(parents=True, exist_ok=True)
    md_path = day_dir / f"{video['video_id']}.md"
    json_path = day_dir / f"{video['video_id']}.json"

    md_content = to_markdown(video["url"], channel_name, data)
    if not md_content:
        raise ValueError(f"to_markdown produced empty content for {video['video_id']}")
    json_content = raw_text or ""

    md_tmp = md_path.with_name(md_path.name + ".tmp")
    json_tmp = json_path.with_name(json_path.name + ".tmp")
    try:
        md_tmp.write_text(md_content, encoding="utf-8")
        json_tmp.write_text(json_content, encoding="utf-8")
        md_tmp.replace(md_path)
        json_tmp.replace(json_path)
    except Exception:
        for tmp in (md_tmp, json_tmp):
            try:
                tmp.unlink(missing_ok=True)
            except Exception:
                pass
        raise
    return md_path


def write_digest_file(
    date_str: str,
    track: str,
    output_filename: str,
    video_ids: list | None = None,
) -> Path | None:
    """Concatenate per-video <video_id>.md files into a single digest file.

    track="rotation" -> output/<date>/<output_filename>
    track="oneoff"   -> output/oneoffs/<date>/<output_filename>

    video_ids=None: include every per-video .md in the folder (the
    aggregate digest). Files whose names start with "digest" are excluded
    so the function doesn't recursively pull its own prior output back in.

    video_ids=[...]: include ONLY those video_ids, in the given order.
    Used for per-run digests where the content should reflect only the
    videos that this specific run processed.

    Returns the path to the written digest, or None if there's nothing to
    publish (folder missing, no per-video .md to include, all candidates
    quoteless). The closing CHECK OTHER YOUTUBE PODCASTS HERE link is
    appended to every digest under a horizontal rule.
    """
    if track == "oneoff":
        day_dir = OUTPUT_DIR / "oneoffs" / date_str
    else:
        day_dir = OUTPUT_DIR / date_str
    if not day_dir.is_dir():
        return None

    if video_ids is None:
        video_md_paths = sorted(
            p for p in day_dir.glob("*.md")
            if p.is_file() and not p.name.startswith("digest")
        )
    else:
        video_md_paths = []
        for vid in video_ids:
            p = day_dir / f"{vid}.md"
            if p.is_file():
                video_md_paths.append(p)
    if not video_md_paths:
        return None

    parts = [f"# HoopsHype YT Quotes — {date_str}", ""]
    first = True
    for md_path in video_md_paths:
        try:
            content = md_path.read_text(encoding="utf-8").strip()
        except Exception:
            continue
        if not content:
            continue
        # Skip videos that processed cleanly but produced zero quotes.
        # Quote headers start with "**<n>. " in the rendered markdown.
        if not re.search(r'(?m)^\*\*\d+\.', content):
            continue
        if content.startswith("# "):
            content = "#" + content  # demote h1 to h2
        if not first:
            parts.append("---")
            parts.append("")
        first = False
        parts.append(content)
        parts.append("")

    if first:
        return None

    parts.append("---")
    parts.append("")
    parts.append(DIGEST_CLOSING_LINE)
    parts.append("")

    digest_path = day_dir / output_filename
    tmp = digest_path.with_name(digest_path.name + ".tmp")
    try:
        tmp.write_text("\n".join(parts), encoding="utf-8")
        tmp.replace(digest_path)
    except Exception:
        try:
            tmp.unlink(missing_ok=True)
        except Exception:
            pass
        raise
    return digest_path


def _reporter_gate_check(merged: dict, require_speakers: list) -> str | None:
    """Returns None when at least one required reporter is present in the
    Gemini output; returns a comma-joined display of the required list
    when the video should be discarded as not-on-topic for this gate.

    The gate matches loosely: case-insensitive substring against any
    speakers_seen entry, any quote.speaker, any text_blocks[].speaker, or
    any names_mentioned entry. For two-token required names a last-name
    fallback kicks in when the surname is distinctive enough (>=7 chars)
    that a substring hit is unlikely to be a false positive.
    """
    if not require_speakers:
        return None
    gathered: set[str] = set()

    def _add(name):
        if not name:
            return
        n = str(name).strip()
        if n:
            gathered.add(n.lower())

    for s in (merged.get("speakers_seen") or []):
        _add(s)
    for q in (merged.get("quotes") or []):
        _add(q.get("speaker"))
        for blk in (q.get("text_blocks") or []):
            _add(blk.get("speaker"))
        for n in (q.get("names_mentioned") or []):
            _add(n)

    DISTINCTIVE_SURNAME_MIN = 7
    for required in require_speakers:
        required_lower = required.lower().strip()
        if not required_lower:
            continue
        if any(required_lower in g for g in gathered):
            return None
        parts = required.split()
        if len(parts) >= 2:
            last = parts[-1].lower()
            if len(last) >= DISTINCTIVE_SURNAME_MIN and any(last in g for g in gathered):
                return None
    return ", ".join(require_speakers)


def process_video(
    client,
    video: dict,
    channel_name: str,
    known_speakers: list | None = None,
    require_speakers: list | None = None,
) -> tuple[str, dict | None]:
    """Run Gemini against one video, write outputs.

    Returns (status, data) where data is the parsed Gemini response on success
    and None otherwise. known_speakers (optional) primes the prompt with
    the channel's recurring-host names so Gemini doesn't substitute
    similar-sounding ones. require_speakers (optional) enforces a
    post-Gemini reporter-gate: if none of the listed names appear in the
    output, the video is discarded with a SKIPPED-reporter-gate marker
    and the run returns status "skipped-reporter-gate" without writing
    md/json artifacts.
    """
    url = video["url"]
    video_id = video["video_id"]
    pub_date = _publish_date(video)
    day_dir = _video_day_dir(video)
    day_dir.mkdir(parents=True, exist_ok=True)

    expected_title = video.get("title") or ""
    known_speakers = list(known_speakers or [])
    duration_secs = int(video.get("duration") or 0)
    meta_log = (
        f"  [meta] {video_id} publish={pub_date} title={expected_title!r} "
        f"duration={duration_secs}s"
    )
    if known_speakers:
        meta_log += f" known_hosts={known_speakers}"
    log(meta_log)

    # Plan the chunking. >MAX_CHUNKS*CHUNK_DURATION_SECS gets the existing
    # too-long treatment; <=CHUNK_DURATION_SECS or unknown gets a single
    # whole-video pass with no video_metadata (identical to pre-chunking
    # behaviour); anything in between becomes 2-4 chunks.
    chunks = _compute_chunks(duration_secs)
    if chunks is None:
        log(f"  too-long on {video_id}: duration {duration_secs}s exceeds "
            f"{MAX_CHUNKS * CHUNK_DURATION_SECS}s ({MAX_CHUNKS}h) chunking cap")
        (day_dir / f"{video_id}.SKIPPED-too-long").write_text("", encoding="utf-8")
        return "too-long", None

    n_chunks = len(chunks)
    chunk_results: list[dict] = []

    for i, (start_off, end_off) in enumerate(chunks):
        chunk_label = f"chunk {i + 1}/{n_chunks}"
        if start_off is not None:
            log(f"  [{chunk_label}] processing {video_id} from {start_off}s to {end_off}s")

        # Per-chunk loop: JSON parse retry sits here, the Gemini API retry
        # is inside call_gemini_with_retry. TransientServerOverload and
        # SpendingCapExhausted propagate past the chunk loop so the whole
        # video bails — siblings + the rest of the queue handle them.
        attempts_parse = 0
        chunk_data = None
        while True:
            try:
                raw_text, _usage = call_gemini_with_retry(
                    client, url, expected_title, known_speakers,
                    start_offset_secs=start_off, end_offset_secs=end_off,
                )
            except (TransientServerOverload, SpendingCapExhausted):
                raise
            except Exception as e:
                status_code = gemini_error_status(e)
                if status_code == 400 or is_token_limit_error(e):
                    # If a single chunk somehow still trips the token limit
                    # (shouldn't with 60-min slices, but be safe), skip the
                    # chunk rather than killing the whole video.
                    log(f"  [{chunk_label}] token-limit / 400 on {video_id}: {e}; skipping chunk")
                else:
                    log(f"  [{chunk_label}] unexpected Gemini error on {video_id}: {e}; skipping chunk")
                break

            try:
                data = json.loads(raw_text)
            except json.JSONDecodeError as e:
                attempts_parse += 1
                log(f"  [{chunk_label}] malformed JSON (attempt {attempts_parse}): {e}")
                if attempts_parse >= 2:
                    log(f"  [{chunk_label}] persistent JSON failure; skipping chunk")
                    break
                continue

            # Per-chunk hallucination guard. A mismatch on one chunk skips
            # only that chunk; other chunks still get their shot.
            echoed_title = (data.get("video_title") or "").strip()
            overlap = _title_word_overlap(expected_title, echoed_title)
            if overlap <= HALLUCINATION_OVERLAP_THRESHOLD:
                log(
                    f"  [{chunk_label}] [hallucination] title mismatch "
                    f"(overlap {overlap:.0%}): expected {expected_title!r}, "
                    f"got {echoed_title!r}; skipping chunk"
                )
                break

            # Translate chunk-relative timestamps to absolute. For the
            # first chunk start_off is 0 (or None for unchunked); the
            # shift is a no-op there.
            chunk_offset = start_off or 0
            if chunk_offset > 0:
                for q in (data.get("quotes") or []):
                    rel_secs = timestamp_to_seconds(q.get("timestamp") or "0:00")
                    q["timestamp"] = _seconds_to_timestamp(chunk_offset + rel_secs)

            chunk_data = data
            break

        if chunk_data is not None:
            chunk_results.append(chunk_data)

    # All chunks failed -> failed-other. _process_one_video records the
    # attempt and writes FAILED.txt only after the retry cap is hit.
    if not chunk_results:
        log(f"  all {n_chunks} chunk(s) failed for {video_id}")
        return "failed-other", None

    # Merge chunks into a single data dict. video_title comes from the
    # first successful chunk (which already passed the hallucination
    # guard); speakers_seen unions across chunks preserving order.
    merged: dict = {
        "video_title": (chunk_results[0].get("video_title") or expected_title).strip(),
        "speakers_seen": [],
        "quotes": [],
    }
    seen_speakers: set = set()
    for d in chunk_results:
        for s in (d.get("speakers_seen") or []):
            if s and s not in seen_speakers:
                seen_speakers.add(s)
                merged["speakers_seen"].append(s)
        merged["quotes"].extend(d.get("quotes") or [])

    # Post-process: split, dedupe, cap at MAX_QUOTES_AFTER_SPLIT
    # (across all chunks combined).
    merged["quotes"] = post_process_quotes(client, merged["quotes"])

    if n_chunks > 1:
        log(f"  merged {n_chunks} chunks for {video_id}: "
            f"{len(chunk_results)} succeeded, "
            f"{len(merged['quotes'])} quotes after post-processing")

    # Reporter-gate: channels like NBA on ESPN post a mix of insider
    # reporting + analyst desk talk. We only want segments where one of
    # the configured reporters appears. Check AFTER post-processing so
    # the lookup sees the final, deduped speaker/name set. On miss,
    # drop the video with a SKIPPED-reporter-gate marker so the next
    # cron doesn't re-queue it.
    require_speakers = list(require_speakers or [])
    if require_speakers:
        miss = _reporter_gate_check(merged, require_speakers)
        if miss is not None:
            log(f"  [reporter-gate] {video_id}: required reporter(s) not present "
                f"({miss}); skipping")
            (day_dir / f"{video_id}.SKIPPED-reporter-gate").write_text("", encoding="utf-8")
            return "skipped-reporter-gate", None

    archived_json = json.dumps(merged, ensure_ascii=False)
    write_outputs(video, channel_name, merged, archived_json)
    return "ok", merged



# --- pressers addition (the only change to the vendored code) ---
PROMPT = PROMPT + '\n\nADDITIONAL RULE (NBA pressers): Only name a speaker who is identified by name in the video (on-screen graphic or chyron, introduced by name, addressed by name) or in the video title. Otherwise write exactly "Unidentified speaker". Never guess a name from voice, appearance, job title or team.'
