"""
Regenerate pressers_v2/ytq_vendor.py from hoopshype-yt-quotes.

Copies, byte for byte and in source order, the extraction + rendering code
of quote_extractor.py (process_video, its chunking, retries, splitter,
write_outputs, to_markdown, _bold_names, _is_unknown_speaker and everything
they depend on), then appends the pressers speaker rule to PROMPT.

    python pressers_v2/tools/vendor_ytq.py /path/to/hoopshype-yt-quotes
"""

import ast
import subprocess
import sys
from pathlib import Path

ROOTS = ["process_video", "write_outputs", "to_markdown"]
EXTRA = ["DIGEST_CLOSING_LINE"]
OUT = Path(__file__).resolve().parent.parent / "ytq_vendor.py"

SPEAKER_RULE = '''

ADDITIONAL RULE (NBA pressers): Only name a speaker who is identified by name in the video (on-screen graphic or chyron, introduced by name, addressed by name) or in the video title. Otherwise write exactly "Unidentified speaker". Never guess a name from voice, appearance, job title or team.'''

HEADER = '''"""
VENDORED from jsierrahoopshype/hoopshype-yt-quotes, branch
claude/youtube-quote-extractor-pcYe7, commit {commit}, file quote_extractor.py.

Generated by pressers_v2/tools/vendor_ytq.py. Do not edit by hand: every
definition below is copied byte for byte so pressers quotes are extracted,
timestamped and rendered exactly like yt-quotes. The only change is the
speaker rule appended to PROMPT at the end of this file.
"""

import json
import math
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from datetime import datetime, timezone
from pathlib import Path

from google.genai import types

'''


def main(src_repo: str) -> None:
    path = Path(src_repo) / "quote_extractor.py"
    src = path.read_text(encoding="utf-8")
    commit = subprocess.run(["git", "-C", src_repo, "rev-parse", "--short", "HEAD"],
                            capture_output=True, text=True).stdout.strip() or "unknown"
    tree = ast.parse(src)
    defs = {}
    for node in tree.body:
        if isinstance(node, (ast.FunctionDef, ast.ClassDef)):
            defs[node.name] = node
        elif isinstance(node, ast.Assign):
            for t in node.targets:
                if isinstance(t, ast.Name):
                    defs[t.id] = node
    seen, stack = set(), list(ROOTS) + EXTRA
    while stack:
        name = stack.pop()
        if name in seen or name not in defs:
            continue
        seen.add(name)
        for sub in ast.walk(defs[name]):
            if isinstance(sub, ast.Name) and sub.id in defs and sub.id not in seen:
                stack.append(sub.id)
    lines = src.splitlines(keepends=True)
    nodes = sorted({id(defs[n]): defs[n] for n in seen}.values(), key=lambda n: n.lineno)
    body = []
    for node in nodes:
        start = node.lineno - 1
        # keep the comment block directly above a definition
        while start > 0 and lines[start - 1].lstrip().startswith("#"):
            start -= 1
        body.append("".join(lines[start:node.end_lineno]))
    out = HEADER.format(commit=commit) + "\n\n".join(body) + "\n\n\n"
    out += "# --- pressers addition (the only change to the vendored code) ---\n"
    out += f"PROMPT = PROMPT + {SPEAKER_RULE!r}\n"
    OUT.write_text(out, encoding="utf-8")
    print(f"wrote {OUT} ({len(nodes)} definitions from {commit})")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else ".")
